### ISSUE TITLE
Поговорить по одному вопросу

### ISSUE THREAD

**Issue by Java-Help** [mohaxspb/MaterialTemplate#1]
Здравствуйте, Юрий. У меня есть сайт java-help.ru. Одному поддерживать его трудно, поэтому я ищу напарника для совместной работы. Может вы сможете им стать? Напишите, пожалуйста, мне на почту imangazaliev.mahach@mail.ru или в ВК http://vk.com/imahach

**Comment by mohaxspb** [comment]
Доброго времени суток!
К сожалению у меня сейчас по своим проектам цейтнот, засим свободного времени нет совсем.
